package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/rs/zerolog/log"
)

type resetStruct struct {
	PkgPath string
	PkgName string
	Name    string
	Fields  []*ast.Field
}

type templateData struct {
	Package string
	Methods string
}

const tpl = `// Code generated by reset generator. DO NOT EDIT.

package {{.Package}}

{{.Methods}}
`

func main() {
	root, err := os.Getwd()
	if err != nil {
		log.Fatal().Err(err).Msg("не удалось получить текущую рабочую директорию")
	}

	fset := token.NewFileSet()
	var targets []resetStruct

	err = filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return err
		}

		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}

			hasMarker := false
			if gd.Doc != nil {
				for _, c := range gd.Doc.List {
					if strings.Contains(c.Text, "generate:reset") {
						hasMarker = true
						break
					}
				}
			}
			if !hasMarker {
				continue
			}

			for _, spec := range gd.Specs {
				ts := spec.(*ast.TypeSpec)
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}

				targets = append(targets, resetStruct{
					PkgPath: filepath.Dir(path),
					PkgName: file.Name.Name,
					Name:    ts.Name.Name,
					Fields:  st.Fields.List,
				})
			}
		}

		return nil
	})
	if err != nil {
		log.Fatal().Err(err).Msg("ошибка обхода файлов проекта")
	}

	type pkgGroup struct {
		pkgName string
		methods []string
	}
	groups := map[string]*pkgGroup{}

	for _, t := range targets {
		g, ok := groups[t.PkgPath]
		if !ok {
			g = &pkgGroup{pkgName: t.PkgName}
			groups[t.PkgPath] = g
		}
		g.methods = append(g.methods, generateResetMethod(t))
	}

	for pkgPath, g := range groups {
		var buf bytes.Buffer

		err := template.Must(template.New("reset").Parse(tpl)).Execute(&buf, templateData{
			Package: g.pkgName,
			Methods: strings.Join(g.methods, "\n\n"),
		})
		if err != nil {
			log.Fatal().Err(err).Msg("ошибка генерации кода reset")
		}

		src, err := format.Source(buf.Bytes())
		if err != nil {
			log.Fatal().Err(err).Msg("ошибка форматирования сгенерированного кода")
		}

		out := filepath.Join(pkgPath, "reset.gen.go")
		if err := os.WriteFile(out, src, 0644); err != nil {
			log.Fatal().Err(err).Msg("не удалось записать файл reset.gen.go")
		}
	}
}

func generateResetMethod(t resetStruct) string {
	body := generateBody(t.Fields)

	return fmt.Sprintf(
		`func (v *%s) Reset() {
	if v == nil {
		return
	}

%s
}
`,
		t.Name,
		body,
	)
}

func generateBody(fields []*ast.Field) string {
	var b strings.Builder

	for _, f := range fields {
		for _, n := range f.Names {
			b.WriteString(generateField(n.Name, f.Type))
		}
	}

	return b.String()
}

func generateField(name string, expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		if t.Obj != nil {
			if decl, ok := t.Obj.Decl.(*ast.TypeSpec); ok {
				return generateField(name, decl.Type)
			}
		}

		if isPrimitive(t.Name) {
			return fmt.Sprintf("\tv.%s = %s\n", name, zeroValue(t.Name))
		}

		return ""

	case *ast.StarExpr:
		if id, ok := t.X.(*ast.Ident); ok {

			if id.Obj != nil {
				if decl, ok := id.Obj.Decl.(*ast.TypeSpec); ok {
					return generatePointerField(name, decl.Type)
				}
			}

			if isPrimitive(id.Name) {
				return fmt.Sprintf("\tif v.%[1]s != nil { *v.%[1]s = %s }\n", name, zeroValue(id.Name))
			}
		}

		return generateResetCall(name)

	case *ast.ArrayType:
		return fmt.Sprintf("\tv.%[1]s = v.%[1]s[:0]\n", name)

	case *ast.MapType:
		return fmt.Sprintf("\tclear(v.%s)\n", name)

	case *ast.InterfaceType:
		return fmt.Sprintf("\tif r, ok := v.%s.(interface{ Reset() }); ok { r.Reset() }\n", name)

	case *ast.SelectorExpr, *ast.StructType:
		return generateResetCall(name)

	default:
		return ""
	}
}

func generatePointerField(name string, expr ast.Expr) string {
	switch t := expr.(type) {

	case *ast.Ident:
		return fmt.Sprintf("\tif v.%[1]s != nil { *v.%[1]s = %s }\n", name, zeroValue(t.Name))

	case *ast.StructType:
		return generateResetCall(name)
	}

	return ""
}

func generateResetCall(name string) string {
	return fmt.Sprintf("\tif r, ok := any(v.%s).(interface{ Reset() }); ok { r.Reset() }\n", name)
}

func isPrimitive(t string) bool {
	switch t {
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32",
		"uint64", "float32", "float64", "bool", "string", "byte", "rune":
		return true
	}
	return false
}

func zeroValue(t string) string {
	switch t {
	case "string":
		return `""`

	case "bool":
		return "false"

	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32",
		"uint64", "float32", "float64", "byte", "rune":
		return "0"
	}

	return "0"
}
